# Generated by Django 5.0.14 on 2026-07-04 12:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VatCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INPUT", "Vorsteuer (auf Aufwand)"),
                            ("OUTPUT", "Umsatzsteuer (auf Ertrag)"),
                            ("NONE", "Keine MWST"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "clearing_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Konto für die MWST-Verbuchung (z.B. Vorsteuer oder Geschuldete MWST).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_codes",
                        to="ledger.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "MWST-Code",
                "verbose_name_plural": "MWST-Codes",
                "ordering": ["code"],
            },
        ),
    ]
