# Generated by Django 5.0.14 on 2026-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mwst_pflichtig",
                    models.BooleanField(
                        default=True,
                        help_text="Wenn deaktiviert, wird die MWST-Auswahl beim Verbuchen ausgeblendet.",
                        verbose_name="MWST-pflichtig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Firmeneinstellung",
                "verbose_name_plural": "Firmeneinstellungen",
            },
        ),
    ]
