# Generated by Django 5.0.14 on 2026-07-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("ledger", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="privatkonto",
            field=models.ForeignKey(
                blank=True,
                help_text="Gegenkonto für Bewegungen, die als privat markiert werden (z.B. private Käufe über die geschäftliche Zahlungsmethode). Wird ohne MWST verbucht und fliesst nicht in Erfolgsrechnung/Auswertung ein. Leer = Konto mit Nummer 2850 wird automatisch verwendet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ledger.account",
                verbose_name="Privatkonto",
            ),
        ),
    ]
