# Generated by Django 5.0.14 on 2026-08-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_companysettings_privatkonto"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="firmenname",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text='Erscheint im Kopf der PDF-Berichte, z.B. "Muster GmbH, Chur".',
                max_length=120,
                verbose_name="Firmenname",
            ),
        ),
    ]
