# Generated by Django 5.0.14 on 2026-09-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_companysettings_firmenname"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysettings",
            name="firmenadresse",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text='Für die Titelseite der Jahresrechnung, z.B. "Musterstrasse 1\\n7000 Chur".',
                max_length=200,
                verbose_name="Firmenadresse",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="treuhand_adresse",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=200,
                verbose_name="Treuhänder Adresse",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="treuhand_name",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=120,
                verbose_name="Treuhänder Name",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="treuhand_telefon",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=50,
                verbose_name="Treuhänder Telefon",
            ),
        ),
        migrations.AddField(
            model_name="companysettings",
            name="treuhand_website",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                max_length=100,
                verbose_name="Treuhänder Website",
            ),
        ),
    ]
