# Generated by Django 5.0.14 on 2026-07-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ledger", "0001_initial"),
        ("vat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="vat_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journal_lines",
                to="vat.vatcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("credit_amount", 0), ("debit_amount__gt", 0)),
                    models.Q(("credit_amount__gt", 0), ("debit_amount", 0)),
                    _connector="OR",
                ),
                name="journalline_debit_xor_credit",
            ),
        ),
    ]
