# Generated by Django 5.0.14 on 2026-09-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalyear",
            name="gewinnruecklage_zuweisung",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Für den Antrag über die Verwendung des Bilanzgewinnes: Betrag, der der gesetzlichen Gewinnreserve zugewiesen wird. Der Rest von Gewinnvortrag + Jahresergebnis gilt als Vortrag auf neue Rechnung. Leer/0 = alles wird vorgetragen.",
                max_digits=12,
                null=True,
                verbose_name="Zuweisung an gesetzliche Gewinnreserve",
            ),
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tree",
                    models.CharField(
                        choices=[
                            ("SALDOBILANZ", "Saldobilanz (nummeriert)"),
                            ("JAHRESRECHNUNG", "Jahresrechnung (sprachlich)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Eindeutiger Code innerhalb des Baums, z.B. "100" (Saldobilanz) oder "FLUESSIGE_MITTEL" (Jahresrechnung).',
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AKTIVA", "Aktiven"),
                            ("PASSIVA", "Passiven"),
                            ("AUFWAND", "Aufwand"),
                            ("ERTRAG", "Ertrag"),
                        ],
                        help_text="Nur für Wurzelgruppen relevant (Aktiven/Passiven bzw. Aufwand/Ertrag).",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="ledger.accountgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontengruppe",
                "verbose_name_plural": "Kontengruppen",
                "ordering": ["tree", "order", "code"],
            },
        ),
        migrations.AddField(
            model_name="account",
            name="jahresrechnung_gruppe",
            field=models.ForeignKey(
                blank=True,
                help_text="Für die vollständige Jahresrechnung-PDF (Titelseite, Anhang, Antrag).",
                limit_choices_to={"tree": "JAHRESRECHNUNG"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jahresrechnung_accounts",
                to="ledger.accountgroup",
                verbose_name="Gruppe (Jahresrechnung)",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="saldobilanz_gruppe",
            field=models.ForeignKey(
                blank=True,
                help_text="Für die gruppierte Bilanz/Erfolgsrechnung-PDF (Zwischentotale).",
                limit_choices_to={"tree": "SALDOBILANZ"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="saldobilanz_accounts",
                to="ledger.accountgroup",
                verbose_name="Gruppe (nummerierte Saldobilanz)",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountgroup",
            constraint=models.UniqueConstraint(
                fields=("tree", "code"), name="uniq_accountgroup_tree_code"
            ),
        ),
    ]
