# Generated by Django 5.0.14 on 2026-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("currency", models.CharField(default="CHF", max_length=3)),
                ("csv_delimiter", models.CharField(default=",", max_length=5)),
                ("csv_date_column", models.CharField(default="Datum", max_length=50)),
                (
                    "csv_amount_column",
                    models.CharField(default="Betrag", max_length=50),
                ),
                (
                    "csv_description_column",
                    models.CharField(default="Beschreibung", max_length=50),
                ),
                (
                    "csv_date_format",
                    models.CharField(default="%d.%m.%Y", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Bankkonto",
                "verbose_name_plural": "Bankkonten",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Bewegung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="CHF", max_length=3)),
                ("description", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV-Import"),
                            ("API", "Bank-Schnittstelle"),
                            ("MANUAL", "Manuell"),
                        ],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                ("dedup_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFFEN", "Offen"),
                            ("BOOKED", "Verbucht"),
                            ("IGNORED", "Ignoriert"),
                        ],
                        default="OFFEN",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bewegung",
                "verbose_name_plural": "Bewegungen",
                "ordering": ["-booking_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "CSV-Import",
                "verbose_name_plural": "CSV-Importe",
                "ordering": ["-imported_at"],
            },
        ),
    ]
