# Generated by Django 5.0.14 on 2026-07-04 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bank", "0001_initial"),
        ("ledger", "0001_initial"),
        ("vat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="bewegung",
            name="assigned_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bewegungen",
                to="ledger.account",
            ),
        ),
        migrations.AddField(
            model_name="bewegung",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bewegungen",
                to="bank.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="bewegung",
            name="journal_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bewegung",
                to="ledger.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="bewegung",
            name="vat_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bewegungen",
                to="vat.vatcode",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="import_batches",
                to="bank.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="imported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="bewegung",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bewegungen",
                to="bank.importbatch",
            ),
        ),
    ]
