# Generated by Django 5.0.14 on 2026-07-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_initial"),
        ("ledger", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="csv_amount_column",
            field=models.CharField(
                default="Betrag", max_length=50, verbose_name="CSV-Spalte Betrag"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="csv_date_column",
            field=models.CharField(
                default="Datum", max_length=50, verbose_name="CSV-Spalte Datum"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="csv_date_format",
            field=models.CharField(
                default="%d.%m.%Y", max_length=20, verbose_name="CSV-Datumsformat"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="csv_delimiter",
            field=models.CharField(
                default=",", max_length=5, verbose_name="CSV-Trennzeichen"
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="csv_description_column",
            field=models.CharField(
                default="Beschreibung",
                max_length=50,
                verbose_name="CSV-Spalte Beschreibung",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(default="CHF", max_length=3, verbose_name="Währung"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="iban",
            field=models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="ledger_account",
            field=models.OneToOneField(
                help_text="Das Konto aus dem Kontenplan, das dieses Bankkonto darstellt (z.B. 1020 – Bank).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_account",
                to="ledger.account",
                verbose_name="Buchhaltungskonto",
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
