# Generated by Django 5.0.14 on 2026-07-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_alter_bankaccount_csv_amount_column_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bewegung",
            name="quittung_erforderlich",
            field=models.BooleanField(
                default=True,
                help_text="Abschalten, wenn für diese Bewegung keine Quittung nötig/verfügbar ist (z.B. Bankgebühren).",
                verbose_name="Quittung erforderlich",
            ),
        ),
    ]
