# Generated by Django 5.0.14 on 2026-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_alter_bankaccount_csv_amount_column_and_more"),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("BANKBELEG", "Bankbeleg / Zahlungsbestätigung"),
                    ("QUITTUNG", "Quittung / Rechnung"),
                    ("SONSTIGES", "Sonstiges"),
                ],
                default="QUITTUNG",
                max_length=20,
                verbose_name="Beleg-Typ",
            ),
        ),
        migrations.AlterField(
            model_name="beleg",
            name="bewegung",
            field=models.ForeignKey(
                blank=True,
                help_text="Leer = liegt im Posteingang und wurde noch keiner Bewegung zugewiesen.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="belege",
                to="bank.bewegung",
            ),
        ),
    ]
