# Generated by Django 5.0.14 on 2026-07-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_beleg_document_type_alter_beleg_bewegung"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="expected_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Für die automatische Zuordnung zu einer Bewegung beim Hochladen im Posteingang.",
                max_digits=12,
                null=True,
                verbose_name="Betrag",
            ),
        ),
        migrations.AddField(
            model_name="beleg",
            name="expected_date",
            field=models.DateField(blank=True, null=True, verbose_name="Datum"),
        ),
    ]
