# Generated by Django 5.0.14 on 2026-07-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_beleg_expected_amount_beleg_expected_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Beleg wurde bereits abgelegt und soll in der Belege-Übersicht ausgeblendet werden können.",
                verbose_name="Nicht mehr anzeigen",
            ),
        ),
    ]
