# Generated by Django 5.0.14 on 2026-07-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_beleg_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="Gesetzt, wenn dieser Beleg über 'an weitere Bewegung anhängen' als Kopie eines anderen Belegs entstanden ist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="copies",
                to="documents.beleg",
            ),
        ),
    ]
