# Generated by Django 5.0.14 on 2026-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_beleg_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Beim Hochladen automatisch aus dem Dokument extrahierter Text (PDF-Text oder OCR), für die Volltextsuche.",
                verbose_name="Erkannter Text",
            ),
        ),
    ]
