# Generated by Django 5.0.14 on 2026-07-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_beleg_extracted_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beleg",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                db_default="",
                default="",
                help_text="Beim Hochladen automatisch aus dem Dokument extrahierter Text (PDF-Text oder OCR), für die Volltextsuche.",
                verbose_name="Erkannter Text",
            ),
        ),
    ]
