# Generated by Django 5.0.14 on 2026-07-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_alter_beleg_extracted_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="beleg",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_default="",
                db_index=True,
                default="",
                help_text="SHA-256 des Dateiinhalts, zur Duplikat-Erkennung.",
                max_length=64,
                verbose_name="Datei-Prüfsumme",
            ),
        ),
    ]
