# Generated by Django 5.0.14 on 2026-07-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_beleg_file_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IgnoredDuplicateHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("ignored_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ignored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ignoriertes Duplikat",
                "verbose_name_plural": "Ignorierte Duplikate",
            },
        ),
    ]
